config/routes.rb
Rails.application.routes.draw do

  resources :letters

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root "static_pages#home"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  mount_griddler
end

app/models/concerns/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_many :letters
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/email_processor.rb
class EmailProcessor
  def initialize(email)
    @to = email.to
    @from = email.from
    @body = email.raw_html

    # @body = email.body

    @subject = email.subject
    @email = email
  end

  def process

    @recip = @to[0][:token].downcase
    @user = User.where(:name => @recip)
    unless @user == nil
      Letter.create!({ content: @body , sender: @email.from[:name], title: @subject, recipient: @recip})
      # @sender = Sender.find_by(name: @email.from[:token] , url: @email.from[:host])
      #   if @sender == nil
      #     @sender = Sender.create({name: @email.from[:token] , url: @email.from[:host]})
      #   end

    end

  end

  private

  def pick_meaningful_recipient(recipients)
    recipients.find { |address| address =~ /@mailtailor.space$/ }
  end

end





#
#
# class EmailProcessor
#
#   def self.process(email)
#     Letter.create(title: "Be cool!",  sender_id: 2, content:
#     "<h1>An email hit the server</h1>")
#
#     Letter.create!({ content: email.body, sender: email.from })
#
#   end
#
# end

app/models/letter.rb
class Letter < ActiveRecord::Base




end

app/models/sender.rb
class Sender < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  has_many :letters



  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/letters_controller.rb
class  LettersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def index

    @user = User.find_by(id: session[:user_id])
    @letters = Letter.find_by(letter_params)


  end


  private
    def letter_params
      params.require(:letter).permit( :sender , :recipient )
    end

end

app/controllers/senders_controller.rb
class  SendersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def index


  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])

      sign_in user
      redirect_to user
      session[:user_id] = user.id
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end

  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to MailTailor!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
      @letters = Letter.where(:recipient => @user.name.downcase) if @user
    @senders = @letters.select(:sender).distinct
  end

  # def show
  #   @user = User.find(params[:id])
  #
  #   @senders = @user.letters.map { |letter| letter.sender }
  # end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute( :remember_token, User.digest(User.new_remember_token) )
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailTailor</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    
    <%= stylesheet_link_tag "style", :media => "all" %>

    <%= csrf_meta_tags %>
  </head>
  <body>
      <div class = "container-fluid">

          <div class = "row page-header" id="header">
              <h1 class = "col-md-4 text-center">Mail Tailor</h1>
              <div class="col-md-2 col-md-offset-5">
                  <% if signed_in? %>
                      <a class="btn" role="button" id="logout" data-toggle="modal" data-method='delete' href="<%= signout_path %>">LOGOUT</a>
                  <% else %>
                      <a class="btn" role="button" id="create" data-toggle="modal" data-target="#createmodal">CREATE</a>
                      <a class="btn" role="button" id="login" data-toggle="modal" data-target="#loginmodal">LOGIN</a>
                  <% end %>
              </div>
          </div>

          <div class= "row">
              <div class="modal fade" id="loginmodal">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><!-- the small little x that closes -->
                              <h4 class="modal-title text-center" id="myModalLabel">LOGIN</h4>
                          </div>
                          <div class="modal-body" id="modal-body">
                                <%= form_for(:session, url: sessions_path) do |f| %>

                                    <%= f.label :email %>
                                    <%= f.text_field :email %>

                                    <%= f.label :password %>
                                    <%= f.password_field :password %>

                                    <%= f.submit("Sign in", :class => 'btn', :id => 'modallog' )%>
                                <% end %>

                          </div>
                      </div>
                  </div>
              </div>
          </div>

          <div class= "row">
              <div class="modal fade" id="createmodal">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                              <h4 class="modal-title text-center" id="myModalLabel">CREATE</h4>
                          </div>



                          <div class="modal-body" id="modal-body">
                                  <form action="/users" method="POST">
                                      <label>Name <input id='name_input' name='user[name]' type='text' placeholder="name"></label>
                                      <label>UserName <input name='user[mtname]' type='text' placeholder="username"></label>
                                      <label>Email <input id='email_input' name='user[email]' type='text' placeholder="email"></label>
                                      <label>Password <input id='password_input' name='user[password]' type='password' placeholder="password"></label>
                                      <label>Confirm Password <input id='password_confirmation_input' name='user[password_confirmation]' type='password' placeholder="confirm password"></label>
                                      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                      <button class="btn" id="modallog">CREATE</button>
                                   </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

      </div> <!-- closes container -->



<%= yield %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/letters/index.html.erb
<% @letters.each do |letter| %>
<div class="col-lg-12" id="content">
    <div id="email">
        <%= letter.title %> <br/>
        <br/>
        <%= letter.content.html_safe %>
        </div>

</div>
<% end %>




<!-- old -->
<h1>Look at all these mails!!</h1>
<br>

<% @letters.each do |letter| %>




  <% @letters.each do |letter|
    if letter.sender_id == sender.id %>

        <%=letter.content%>

      <br>
    <%end%>


    <%end%>

  <br>
<%end%>

app/views/senders/index.html.erb
<h1>Look at all these mails!!</h1>
<br>
<% if @senders %>
  <% @senders.each do |sender| %>

  <%= sender.name %><br>
  <%= sender.url %>

  <%end%>

  <% @senders.each do |sender| %>

    <h2><%= sender.name %></h2>
    <h3><%= sender.url %></h3>
    <% @letters.each do |letter|
      if letter.sender_id == sender.id %>
        <%=letter.content.html_safe%>
        <br>
      <%end%>
      <br>

      <%end%>
  <%end%>
  <hr>
  <br><br><br><br><br><br>
  <h1>And now just the mail!</h1>
  <br><br>

  <% @letters.each do |letter| %>
    <h4>letter</h4>
    <%=letter.content%>
    <%=letter.title%>
    <%=letter.id%>
    <br>
  <% end %>
<% end %>

<%= link_to sender.sender,  letters_path + '?sender=' + sender.sender%>

app/views/static_pages/home.html.erb
<h1>Welcome to MailTailor</h1>

<p>Some awesomeness goes here</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>

<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="dashboardstyle.css">
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/simple-sidebar.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>



  <div class = "container-fluid">

     <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" id="logo">
                    <a href="index.html">
                        MAIL THING
                    </a>
                </li>

                <li id="catselect">
                    <button>Sales</button><button>News</button><button>Account</button>
                </li>

                <li>
                    <input placeholder="SEARCH" id="search">
                </li>
                <% @senders.each do |sender| %>
                  <li>
                      <span id = "<%= sender.sender.gsub(" " , "").gsub('.' , "") %>"><%= sender.sender %></span>
                      <button id =  "delete<%= sender.sender.gsub(" " , "").gsub('.' , "") %>">DELETE</button>

                  </li>
                <% end %>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->


        <!-- Page Content -->
          <div id="page-content-wrapper">
              <div class="container-fluid">
                  <div class="row">
                      <nav class="navbar navbar-default navbar-fixed-top" id="nav">
                          <div class="container-fluid">
                              <div class="navbar-header">
                                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                      <ul class="nav navbar-nav">
                                          <li><h3 id="sender">SENDER</h3></li>
                                          <li class="dropdown" id="dropdown">
                                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">MAIL TYPE <span class="caret"></span></a>
                                              <ul class="dropdown-menu" role="menu">
                                                  <li><a href="#">SALES</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">NEWS</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">ACCOUNT</a></li>
                                                  <li class="divider"></li>
                                              </ul>
                                          </li>
                                      </ul>
                                      <input type="text" placeholder="SEARCH" id="searchtop">
                                  </div><!-- /.navbar-collapse -->
                              </div><!-- /.container-fluid -->
                          </nav>
                          <div id="mailDis">


                            <% @letters.each do |letter| %>
                            <div class="col-lg-12" id="content">
                                <div id="email" class = "letterDiv class<%= letter.sender.gsub(" " , "").gsub('.' , "")%>">
                                    <%= letter.title %> <br/>
                                    <br/>
                                    <%= letter.content.html_safe %>
                                    </div>

                            </div>
                            <% end %>
                          </div>
                      </div>
                  </div>
              </div><!-- /#page-content-wrapper -->
          </div> <!-- closes container -->
  <!-- Bootstrap JS -->

  <!--  dialog pop ups -->
  <!--  dialog pop ups were an  -->


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script>
    var sendClassArray = [
      <% @senders.each do |sender| %>
        "class<%= sender.sender.gsub(" " , "").gsub('.' , "") %>" ,
      <% end %>
    ]

    var mailDis = document.getElementById("mailDis");

    $( document ).ready(function() {

  <% @senders.each do |sender| %>

    var <%= 'get' + sender.sender.gsub(" " , "").gsub("." , "") %> = document.getElementById("<%= sender.sender.gsub(" " , "").gsub('.' , "") %>");


    $("#<%=sender.sender.gsub(' ' , '').gsub('.' , '') %>").click(function(){

            $("#<%=sender.sender.gsub(' ' , '').gsub('.' , '') %>").parent().toggleClass("changebackground");

            $(".class<%= sender.sender.gsub(' ' , '').gsub('.' , '') %>").toggle();

        });






          $("#delete<%= sender.sender.gsub(' ' , '').gsub('.' , '') %>").click(function() {
            var kill = window.confirm("are you sure to delete?");
            if (kill==true){
              $("#<%=sender.sender.gsub(' ' , '').gsub('.' , '') %>").remove();
              $(".class<%= sender.sender.gsub(' ' , '').gsub('.' , '') %>").remove();
            };
        });
    });


  <% end %>
});

  </script>


  </body>
  </html>

app/views/users/show_alpha.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="dashboardstyle.css">
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/simple-sidebar.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>



  <div class = "container-fluid">

     <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" id="logo">
                    <a href="index.html">
                        MAIL THING
                    </a>
                </li>

                <li id="emailside">
                    EMAIL ADDRESS
                </li>

                <li>
                    <input placeholder="SEARCH" id="search">
                </li>
                <% @senders.each do |sender| %>
                  <li>
                      <span id = "<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>"><%= sender.display_name %></span>
                      <button id =  "delete<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>">DELETE</button>

                  </li>
                <% end %>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->


        <!-- Page Content -->
          <div id="page-content-wrapper">
              <div class="container-fluid">
                  <div class="row">
                      <nav class="navbar navbar-default navbar-fixed-top" id="nav">
                          <div class="container-fluid">
                              <div class="navbar-header">
                                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                      <ul class="nav navbar-nav">
                                          <li><h3 id="sender">SENDER</h3></li>
                                          <li class="dropdown" id="dropdown">
                                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">MAIL TYPE <span class="caret"></span></a>
                                              <ul class="dropdown-menu" role="menu">
                                                  <li><a href="#">SALES</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">NEWS</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">ACCOUNT</a></li>
                                                  <li class="divider"></li>
                                              </ul>
                                          </li>
                                      </ul>
                                      <input type="text" placeholder="SEARCH" id="searchtop">
                                  </div><!-- /.navbar-collapse -->
                              </div><!-- /.container-fluid -->
                          </nav>
                          <div id="mailDis">


                            <% @user.letters.each do |letter| %>
                            <div class="col-lg-12" id="content">
                                <div id="email" class = "letterDiv class<%= letter.sender.gsub(" " , "").gsub('.' , "")%>">
                                    <%= letter.title %> <br/>
                                    <br/>
                                    <%= letter.content.html_safe %>
                                    </div>

                            </div>
                            <% end %>
                          </div>
                      </div>
                  </div>
              </div><!-- /#page-content-wrapper -->
          </div> <!-- closes container -->
  <!-- Bootstrap JS -->

  <!--  dialog pop ups -->
  <!--  dialog pop ups were an  -->


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script>
    var sendClassArray = [
      <% @senders.each do |sender| %>
        "class<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>" ,
      <% end %>
    ]

    var mailDis = document.getElementById("mailDis");

    $( document ).ready(function() {

  <% @senders.each do |sender| %>

    var <%= 'get' + sender.display_name.gsub(" " , "").gsub("." , "") %> = document.getElementById("<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>");


    $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").click(function(){

            $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().toggleClass("changebackground");

            $(".class<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").toggle();

        });






          $("#delete<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").click(function() {
            var kill = window.confirm("are you sure to delete?");
            if (kill==true){
              $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").remove();
              $(".class<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").remove();
            };
        });
    


  <% end %>
});

  </script>


  </body>
  </html>